// ticket-web-app/vue-version/src/views/Signup.vue
<template>
  <main class="container" style="min-height:calc(100vh - 120px);display:flex;align-items:center;justify-content:center;padding:48px 16px">
    <div class="card" style="width:100%;max-width:480px">
      <div style="padding:18px">
        <h1 style="font-size:28px;margin:0">Create Your Account</h1>
        <p style="color:var(--color-muted);margin-top:8px">Get your tickets in just a few taps.</p>
        <form @submit.prevent="submit" style="margin-top:18px;display:grid;gap:12px">
          <!-- Full name removed for consistency across frameworks -->
          <label style="display:flex;flex-direction:column;gap:6px">
            <span style="font-size:13px;color:#374151">Email address</span>
            <input v-model="email" class="input focus-outline" placeholder="you@example.com" />
          </label>
          <label style="display:flex;flex-direction:column;gap:6px">
            <span style="font-size:13px;color:#374151">Password</span>
            <input type="password" v-model="password" class="input focus-outline" />
            <small style="font-size:12px;color:var(--color-muted)">Must be at least 8 characters.</small>
          </label>
          <button class="button" type="submit" style="width:100%">Create Account</button>
          <p style="text-align:center;margin:0;font-size:14px;color:var(--color-muted)">Already have an account? <button type="button" @click.prevent="cancel" style="background:none;border:none;color:var(--primary);font-weight:700;cursor:pointer">Log In</button></p>
        </form>
      </div>
    </div>
  </main>
</template>

<script>
import { ref } from 'vue'
import { login } from '../utils/auth'
export default {
  emits:['toast'],
  setup(_, {emit}){
    const email=ref('')
    const password=ref('')
    function submit(){ login({email:email.value}); emit('toast','Account created'); window.location.hash='#/dashboard' }
    function cancel(){ window.location.hash='#/auth/login' }
    return {email,password,submit,cancel}
  }
}
</script>

// ticket-web-app/react-version/src/pages/Signup.jsx
import React, {useState} from 'react'
import {login} from '../utils/auth'

export default function Signup({onNavigate,showToast}){
  const [email,setEmail]=useState('')
  const [password,setPassword]=useState('')
  const [errors,setErrors]=useState({})

  function validate(){
    const e={}
    if(!email) e.email='Email required'
    if(!password) e.password='Password required'
    setErrors(e)
    return Object.keys(e).length===0
  }

  function submit(e){
    e.preventDefault()
    if(!validate()) return
    login({email})
    showToast('Account created')
    window.location.hash='#/dashboard'
  }

  return (
    <main className="container" style={{minHeight:'calc(100vh - 120px)',display:'flex',alignItems:'center',justifyContent:'center',padding:'48px 16px'}}>
      <div className="card" style={{width:'100%',maxWidth:480}}>
        <div style={{padding:18}}>
          <h1 style={{fontSize:28,margin:0}}>Create Your Account</h1>
          <p style={{color:'var(--color-muted)',marginTop:8}}>Get your tickets in just a few taps.</p>
          <form onSubmit={submit} style={{marginTop:18,display:'grid',gap:12}}>
            {/* Full name removed for consistency across frameworks */}
            <label style={{display:'flex',flexDirection:'column',gap:6}}>
              <span style={{fontSize:13,color:'#374151'}}>Email address</span>
              <input className="input focus-outline" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" />
            </label>
            <label style={{display:'flex',flexDirection:'column',gap:6}}>
              <span style={{fontSize:13,color:'#374151'}}>Password</span>
              <input type="password" className="input focus-outline" value={password} onChange={e=>setPassword(e.target.value)} />
              <small style={{fontSize:12,color:'var(--color-muted)'}}>Must be at least 8 characters.</small>
            </label>
            <button className="button" type="submit" style={{width:'100%'}}>Create Account</button>
            <p style={{textAlign:'center',margin:0,fontSize:14,color:'var(--color-muted)'}}>Already have an account? <button type="button" onClick={()=>onNavigate('/auth/login')} style={{background:'none',border:'none',color:'var(--primary)',fontWeight:700,cursor:'pointer'}}>Log In</button></p>
          </form>
        </div>
      </div>
    </main>
  )
}
